# -*- coding: utf-8 -*-
"""fizz_buzz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/EngOsamaHaikal/fizz_buzz-function/blob/main/fizz_buzz.ipynb
"""

def fizz_buzz():
    dic={} 
    for i in range(1, 101):
        if i % 3 == 0 and i % 5 == 0:
            d={i:"fizz_buzz"}
            dic.update(d)
        elif i % 3 == 0:
            d={i:"fizz"}
            dic.update(d)
        elif i % 5 == 0:
            d={i:"buzz"}
            dic.update(d)
        else:
            d={i:"None"}
            dic.update(d)
    return dic

fizz_buzz()